language: r
cache: packages

#Define multiple R-versions:
r:
  - oldrel
  - release

repos:
  CRAN: https://cloud.r-project.org
  
r_github_packages:
  - jimhester/covr
  
after_success:
  - Rscript -e 'library(covr); covr::codecov(type = "all")'

#after_failure:
#  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
