language: r
cache: packages

#Define multiple R-versions:
#  - oldrel
#  - release

repos:
  CRAN: https://cloud.r-project.org
  
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); coveralls(type = "all")'

#after_failure:
#  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
